apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bbp-dev

resources:
  - namespace.yaml
  - mock-api-configmap.yaml
  - pipeline-configmap.yaml
  - mock-api-deployment.yaml
  - mock-api-service.yaml
  - pipeline-job.yaml
