apiVersion: v1
kind: ConfigMap
metadata:
  name: bbp-mock-api-config
  labels:
    app.kubernetes.io/name: bbp-mock-api
    app.kubernetes.io/part-of: bbp-final-pro-framework
data:
  ENV: dev
  API_RUNTIME_CONTEXT: local
  API_URL: http://bbp-mock-api:18080/mock-six-api
  API_SCHEME: http
  API_HOST: bbp-mock-api
  API_PORT: "18080"
  API_BASE_PATH: /mock-six-api
  API_HEALTH_PATH: /health
  API_LOGIN_PATH: /login
  API_UPLOAD_PATH: /upload
  API_TIMEOUT_SECONDS: "15"
  MOCK_API_BIND_HOST: 0.0.0.0
  MOCK_API_BIND_PORT: "18080"
  MOCK_API_GRPC_BIND_HOST: 0.0.0.0
  MOCK_API_GRPC_BIND_PORT: "50061"
  MOCK_STORAGE_DIR: mock_api_uploads
