apiVersion: v1
kind: Service
metadata:
  name: bbp-mock-api
  labels:
    app.kubernetes.io/name: bbp-mock-api
    app.kubernetes.io/part-of: bbp-final-pro-framework
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bbp-mock-api
  ports:
    - name: http
      port: 18080
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 50061
      targetPort: grpc
      protocol: TCP
