apiVersion: v1
kind: Secret
metadata:
  name: bbp-mock-api-credentials
  labels:
    app.kubernetes.io/part-of: bbp-final-pro-framework
type: Opaque
stringData:
  API_USERNAME: mock-user
  API_PASSWORD: mock-pass
  MOCK_API_USERNAME: mock-user
  MOCK_API_PASSWORD: mock-pass
